import { LogRecord } from "../src/types/log";

function ago(ms: number): string {
  return new Date(Date.now() - ms).toISOString();
}
const m = 60_000;
const h = 3_600_000;

export const MOCK_LOGS: LogRecord[] = [
  {
    timestamp: ago(2 * m),
    loglevel: "ERROR",
    content: "NullPointerException in PaymentService.processTransaction() at line 142",
    "log.source": "/var/log/payment-service/app.log",
    "service.name": "payment-service",
    "dt.entity.host": "HOST-abc123",
    status: "ERROR",
  },
  {
    timestamp: ago(5 * m),
    loglevel: "ERROR",
    content: "Failed to connect to database: Connection refused (host=db-primary:5432, retries=3)",
    "log.source": "/var/log/order-service/app.log",
    "service.name": "order-service",
    "dt.entity.host": "HOST-def456",
    status: "ERROR",
  },
  {
    timestamp: ago(12 * m),
    loglevel: "WARN",
    content: "Response time exceeded threshold: 3200ms (threshold=2000ms) for GET /api/v2/products",
    "log.source": "/var/log/api-gateway/access.log",
    "service.name": "api-gateway",
    "dt.entity.host": "HOST-ghi789",
    status: "SLOW",
  },
  {
    timestamp: ago(15 * m),
    loglevel: "ERROR",
    content: "Unhandled promise rejection in Lambda function processOrders: TypeError: Cannot read properties of undefined",
    "log.source": "aws-lambda://process-orders",
    "service.name": "order-processor-lambda",
    "dt.entity.host": "HOST-lambda001",
    status: "ERROR",
  },
  {
    timestamp: ago(20 * m),
    loglevel: "INFO",
    content: "Deployment completed successfully: order-service v2.4.1 → v2.4.2 (canary: 10%)",
    "log.source": "/var/log/deploy-agent/events.log",
    "service.name": "deploy-agent",
    "dt.entity.host": "HOST-ci001",
    status: "OK",
  },
  {
    timestamp: ago(28 * m),
    loglevel: "WARN",
    content: "Memory usage at 87% on pod user-service-7d4b9c-xkv2p (limit: 512Mi, used: 445Mi)",
    "log.source": "k8s://namespace/production/user-service",
    "service.name": "user-service",
    "dt.entity.host": "HOST-k8s-node-03",
    status: "WARNING",
  },
  {
    timestamp: ago(35 * m),
    loglevel: "ERROR",
    content: "Authentication token expired. User session invalidated. userId=usr_882kd, tokenAge=3601s",
    "log.source": "/var/log/auth-service/app.log",
    "service.name": "auth-service",
    "dt.entity.host": "HOST-auth01",
    status: "AUTH_ERROR",
  },
  {
    timestamp: ago(42 * m),
    loglevel: "DEBUG",
    content: "Cache miss for key: product_catalog_page_3 — fetching from origin",
    "log.source": "/var/log/cache-service/debug.log",
    "service.name": "cache-service",
    "dt.entity.host": "HOST-cache01",
    status: "OK",
  },
  {
    timestamp: ago(1 * h),
    loglevel: "ERROR",
    content: "Kafka consumer lag exceeded limit: topic=order-events, partition=2, lag=15820 messages",
    "log.source": "/var/log/kafka-consumer/app.log",
    "service.name": "order-consumer",
    "dt.entity.host": "HOST-kafka01",
    status: "LAG",
  },
  {
    timestamp: ago(1 * h + 10 * m),
    loglevel: "INFO",
    content: "Scheduled job completed: cleanup-expired-sessions removed 2340 records in 1.2s",
    "log.source": "/var/log/scheduler/jobs.log",
    "service.name": "job-scheduler",
    "dt.entity.host": "HOST-worker01",
    status: "OK",
  },
  {
    timestamp: ago(1 * h + 25 * m),
    loglevel: "WARN",
    content: "Rate limit approaching for external API: stripe.com — 85/100 requests used (window=60s)",
    "log.source": "/var/log/billing-service/app.log",
    "service.name": "billing-service",
    "dt.entity.host": "HOST-billing01",
    status: "RATE_LIMIT",
  },
  {
    timestamp: ago(1 * h + 45 * m),
    loglevel: "FATAL",
    content: "Out of memory: JVM heap space exhausted. Initiating emergency restart. Service: inventory-service",
    "log.source": "/var/log/inventory-service/app.log",
    "service.name": "inventory-service",
    "dt.entity.host": "HOST-inv02",
    status: "FATAL",
  },
  {
    timestamp: ago(2 * h),
    loglevel: "ERROR",
    content: "SSL certificate will expire in 7 days: *.internal.company.com (expires 2026-04-19)",
    "log.source": "/var/log/cert-monitor/alerts.log",
    "service.name": "cert-monitor",
    "dt.entity.host": "HOST-infra01",
    status: "CERT_EXPIRY",
  },
  {
    timestamp: ago(2 * h + 30 * m),
    loglevel: "INFO",
    content: "Feature flag 'new_checkout_flow' enabled for 25% of users (experiment: checkout-v2)",
    "log.source": "/var/log/feature-flags/events.log",
    "service.name": "feature-flag-service",
    "dt.entity.host": "HOST-ff01",
    status: "OK",
  },
  {
    timestamp: ago(3 * h),
    loglevel: "WARN",
    content: "Disk space on HOST-db-primary at 79% (used: 395GB / 500GB). Consider cleanup.",
    "log.source": "/var/log/system/diskmonitor.log",
    "service.name": "system-monitor",
    "dt.entity.host": "HOST-db-primary",
    status: "WARNING",
  },
  {
    timestamp: ago(3 * h + 15 * m),
    loglevel: "ERROR",
    content: "GraphQL resolver error: Cannot query field 'discountCode' on type 'CartItem'. Schema mismatch.",
    "log.source": "/var/log/graphql-api/errors.log",
    "service.name": "graphql-api",
    "dt.entity.host": "HOST-api02",
    status: "SCHEMA_ERROR",
  },
  {
    timestamp: ago(4 * h),
    loglevel: "DEBUG",
    content: "Incoming request: POST /api/v1/checkout — userId=usr_991kx, cartId=cart_77abc, items=4",
    "log.source": "/var/log/checkout-service/debug.log",
    "service.name": "checkout-service",
    "dt.entity.host": "HOST-checkout01",
    status: "OK",
  },
  {
    timestamp: ago(4 * h + 30 * m),
    loglevel: "INFO",
    content: "Autoscaling triggered: order-service scaled from 3 → 6 replicas (CPU: 78%)",
    "log.source": "k8s://namespace/production/hpa-events",
    "service.name": "order-service",
    "dt.entity.host": "HOST-k8s-node-01",
    status: "SCALING",
  },
  {
    timestamp: ago(5 * h),
    loglevel: "ERROR",
    content: "S3 upload failed: AccessDenied — bucket=user-avatars-prod, key=uploads/usr_44xyz/avatar.jpg",
    "log.source": "/var/log/media-service/app.log",
    "service.name": "media-service",
    "dt.entity.host": "HOST-media01",
    status: "ACCESS_DENIED",
  },
  {
    timestamp: ago(6 * h),
    loglevel: "INFO",
    content: "Daily metrics report generated: 42,810 orders processed, avg latency 210ms, error rate 0.3%",
    "log.source": "/var/log/analytics/daily-report.log",
    "service.name": "analytics-service",
    "dt.entity.host": "HOST-analytics01",
    status: "OK",
  },
];
